package threeadd.packetEventsSK.util.registry;

import com.github.retrooper.packetevents.event.PacketReceiveEvent;
import com.github.retrooper.packetevents.event.PacketSendEvent;
import com.github.retrooper.packetevents.event.ProtocolPacketEvent;
import com.github.retrooper.packetevents.protocol.packettype.PacketType;
import com.github.retrooper.packetevents.protocol.packettype.PacketTypeCommon;
import com.github.retrooper.packetevents.wrapper.PacketWrapper;
import com.github.retrooper.packetevents.wrapper.play.client.*;
import com.github.retrooper.packetevents.wrapper.play.server.*;
import com.github.retrooper.packetevents.wrapper.handshaking.client.*;
import com.github.retrooper.packetevents.wrapper.login.client.*;
import com.github.retrooper.packetevents.wrapper.login.server.*;
import com.github.retrooper.packetevents.wrapper.configuration.client.*;
import com.github.retrooper.packetevents.wrapper.configuration.server.*;
import com.github.retrooper.packetevents.wrapper.status.client.*;
import com.github.retrooper.packetevents.wrapper.status.server.*;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

// This class was obviously auto generated and SHOULD NOT BE ALTERED MANUALLY
public class EventPacketMapper {

    private static final Map<PacketTypeCommon, Function<ProtocolPacketEvent, PacketWrapper<?>>> map = new HashMap<>();

    static {
        map.put(PacketType.Play.Server.SET_COMPRESSION, e -> new WrapperPlayServerSetCompression((PacketSendEvent) e));
        map.put(PacketType.Play.Server.MAP_CHUNK_BULK, e -> new WrapperPlayServerChunkDataBulk((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_ENTITY_NBT, e -> new WrapperPlayServerUpdateEntityNBT((PacketSendEvent) e));
        map.put(PacketType.Play.Server.USE_BED, e -> new WrapperPlayServerUseBed((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SPAWN_WEATHER_ENTITY, e -> new WrapperPlayServerSpawnWeatherEntity((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TITLE, e -> new WrapperPlayServerSetTitleSubtitle((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WORLD_BORDER, e -> new WrapperPlayServerWorldBorder((PacketSendEvent) e));
        map.put(PacketType.Play.Server.COMBAT_EVENT, e -> new WrapperPlayServerCombatEvent((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_MOVEMENT, e -> new WrapperPlayServerEntityMovement((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SPAWN_LIVING_ENTITY, e -> new WrapperPlayServerSpawnLivingEntity((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SPAWN_PAINTING, e -> new WrapperPlayServerSpawnPainting((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ACKNOWLEDGE_PLAYER_DIGGING, e -> new WrapperPlayServerAcknowledgePlayerDigging((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CHAT_PREVIEW_PACKET, e -> new WrapperPlayServerChatPreview((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_CHAT_HEADER, e -> new WrapperPlayServerPlayerChatHeader((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_INFO, e -> new WrapperPlayServerPlayerInfo((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DISPLAY_CHAT_PREVIEW, e -> new WrapperPlayServerSetDisplayChatPreview((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_ENABLED_FEATURES, e -> new WrapperPlayServerUpdateEnabledFeatures((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SPAWN_PLAYER, e -> new WrapperPlayServerSpawnPlayer((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WINDOW_CONFIRMATION, e -> new WrapperPlayServerWindowConfirmation((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SPAWN_ENTITY, e -> new WrapperPlayServerSpawnEntity((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SPAWN_EXPERIENCE_ORB, e -> new WrapperPlayServerSpawnExperienceOrb((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_ANIMATION, e -> new WrapperPlayServerEntityAnimation((PacketSendEvent) e));
        map.put(PacketType.Play.Server.STATISTICS, e -> new WrapperPlayServerStatistics((PacketSendEvent) e));
        map.put(PacketType.Play.Server.BLOCK_BREAK_ANIMATION, e -> new WrapperPlayServerBlockBreakAnimation((PacketSendEvent) e));
        map.put(PacketType.Play.Server.BLOCK_ENTITY_DATA, e -> new WrapperPlayServerBlockEntityData((PacketSendEvent) e));
        map.put(PacketType.Play.Server.BLOCK_ACTION, e -> new WrapperPlayServerBlockAction((PacketSendEvent) e));
        map.put(PacketType.Play.Server.BLOCK_CHANGE, e -> new WrapperPlayServerBlockChange((PacketSendEvent) e));
        map.put(PacketType.Play.Server.BOSS_BAR, e -> new WrapperPlayServerBossBar((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SERVER_DIFFICULTY, e -> new WrapperPlayServerDifficulty((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CLEAR_TITLES, e -> new WrapperPlayServerClearTitles((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TAB_COMPLETE, e -> new WrapperPlayServerTabComplete((PacketSendEvent) e));
        map.put(PacketType.Play.Server.MULTI_BLOCK_CHANGE, e -> new WrapperPlayServerMultiBlockChange((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DECLARE_COMMANDS, e -> new WrapperPlayServerDeclareCommands((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CLOSE_WINDOW, e -> new WrapperPlayServerCloseWindow((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WINDOW_ITEMS, e -> new WrapperPlayServerWindowItems((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WINDOW_PROPERTY, e -> new WrapperPlayServerWindowProperty((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_SLOT, e -> new WrapperPlayServerSetSlot((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_COOLDOWN, e -> new WrapperPlayServerSetCooldown((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLUGIN_MESSAGE, e -> new WrapperPlayServerPluginMessage((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DISCONNECT, e -> new WrapperPlayServerDisconnect((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_STATUS, e -> new WrapperPlayServerEntityStatus((PacketSendEvent) e));
        map.put(PacketType.Play.Server.EXPLOSION, e -> new WrapperPlayServerExplosion((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UNLOAD_CHUNK, e -> new WrapperPlayServerUnloadChunk((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CHANGE_GAME_STATE, e -> new WrapperPlayServerChangeGameState((PacketSendEvent) e));
        map.put(PacketType.Play.Server.OPEN_HORSE_WINDOW, e -> new WrapperPlayServerOpenHorseWindow((PacketSendEvent) e));
        map.put(PacketType.Play.Server.INITIALIZE_WORLD_BORDER, e -> new WrapperPlayServerInitializeWorldBorder((PacketSendEvent) e));
        map.put(PacketType.Play.Server.KEEP_ALIVE, e -> new WrapperPlayServerKeepAlive((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CHUNK_DATA, e -> new WrapperPlayServerChunkData((PacketSendEvent) e));
        map.put(PacketType.Play.Server.EFFECT, e -> new WrapperPlayServerEffect((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PARTICLE, e -> new WrapperPlayServerParticle((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_LIGHT, e -> new WrapperPlayServerUpdateLight((PacketSendEvent) e));
        map.put(PacketType.Play.Server.JOIN_GAME, e -> new WrapperPlayServerJoinGame((PacketSendEvent) e));
        map.put(PacketType.Play.Server.MAP_DATA, e -> new WrapperPlayServerMapData((PacketSendEvent) e));
        map.put(PacketType.Play.Server.MERCHANT_OFFERS, e -> new WrapperPlayServerMerchantOffers((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_RELATIVE_MOVE, e -> new WrapperPlayServerEntityRelativeMove((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_RELATIVE_MOVE_AND_ROTATION, e -> new WrapperPlayServerEntityRelativeMoveAndRotation((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_ROTATION, e -> new WrapperPlayServerEntityRotation((PacketSendEvent) e));
        map.put(PacketType.Play.Server.VEHICLE_MOVE, e -> new WrapperPlayServerVehicleMove((PacketSendEvent) e));
        map.put(PacketType.Play.Server.OPEN_BOOK, e -> new WrapperPlayServerOpenBook((PacketSendEvent) e));
        map.put(PacketType.Play.Server.OPEN_WINDOW, e -> new WrapperPlayServerOpenWindow((PacketSendEvent) e));
        map.put(PacketType.Play.Server.OPEN_SIGN_EDITOR, e -> new WrapperPlayServerOpenSignEditor((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PING, e -> new WrapperPlayServerPing((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CRAFT_RECIPE_RESPONSE, e -> new WrapperPlayServerCraftRecipeResponse((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_ABILITIES, e -> new WrapperPlayServerPlayerAbilities((PacketSendEvent) e));
        map.put(PacketType.Play.Server.END_COMBAT_EVENT, e -> new WrapperPlayServerEndCombatEvent((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTER_COMBAT_EVENT, e -> new WrapperPlayServerEnterCombatEvent((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DEATH_COMBAT_EVENT, e -> new WrapperPlayServerDeathCombatEvent((PacketSendEvent) e));
        map.put(PacketType.Play.Server.FACE_PLAYER, e -> new WrapperPlayServerFacePlayer((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_POSITION_AND_LOOK, e -> new WrapperPlayServerPlayerPositionAndLook((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DESTROY_ENTITIES, e -> new WrapperPlayServerDestroyEntities((PacketSendEvent) e));
        map.put(PacketType.Play.Server.REMOVE_ENTITY_EFFECT, e -> new WrapperPlayServerRemoveEntityEffect((PacketSendEvent) e));
        map.put(PacketType.Play.Server.RESOURCE_PACK_SEND, e -> new WrapperPlayServerResourcePackSend((PacketSendEvent) e));
        map.put(PacketType.Play.Server.RESPAWN, e -> new WrapperPlayServerRespawn((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_HEAD_LOOK, e -> new WrapperPlayServerEntityHeadLook((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SELECT_ADVANCEMENTS_TAB, e -> new WrapperPlayServerSelectAdvancementsTab((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ACTION_BAR, e -> new WrapperPlayServerActionBar((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WORLD_BORDER_CENTER, e -> new WrapperPlayServerWorldBorderCenter((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WORLD_BORDER_LERP_SIZE, e -> new WrapperPlayWorldBorderLerpSize((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WORLD_BORDER_SIZE, e -> new WrapperPlayServerWorldBorderSize((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WORLD_BORDER_WARNING_DELAY, e -> new WrapperPlayWorldBorderWarningDelay((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WORLD_BORDER_WARNING_REACH, e -> new WrapperPlayServerWorldBorderWarningReach((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CAMERA, e -> new WrapperPlayServerCamera((PacketSendEvent) e));
        map.put(PacketType.Play.Server.HELD_ITEM_CHANGE, e -> new WrapperPlayServerHeldItemChange((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_VIEW_POSITION, e -> new WrapperPlayServerUpdateViewPosition((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_VIEW_DISTANCE, e -> new WrapperPlayServerUpdateViewDistance((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SPAWN_POSITION, e -> new WrapperPlayServerSpawnPosition((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DISPLAY_SCOREBOARD, e -> new WrapperPlayServerDisplayScoreboard((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_METADATA, e -> new WrapperPlayServerEntityMetadata((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ATTACH_ENTITY, e -> new WrapperPlayServerAttachEntity((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_VELOCITY, e -> new WrapperPlayServerEntityVelocity((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_EQUIPMENT, e -> new WrapperPlayServerEntityEquipment((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_EXPERIENCE, e -> new WrapperPlayServerSetExperience((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_HEALTH, e -> new WrapperPlayServerUpdateHealth((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SCOREBOARD_OBJECTIVE, e -> new WrapperPlayServerScoreboardObjective((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_PASSENGERS, e -> new WrapperPlayServerSetPassengers((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TEAMS, e -> new WrapperPlayServerTeams((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_SCORE, e -> new WrapperPlayServerUpdateScore((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_SIMULATION_DISTANCE, e -> new WrapperPlayServerUpdateSimulationDistance((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_TITLE_SUBTITLE, e -> new WrapperPlayServerSetTitleSubtitle((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TIME_UPDATE, e -> new WrapperPlayServerTimeUpdate((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_TITLE_TEXT, e -> new WrapperPlayServerSetTitleText((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_TITLE_TIMES, e -> new WrapperPlayServerSetTitleTimes((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_SOUND_EFFECT, e -> new WrapperPlayServerEntitySoundEffect((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SOUND_EFFECT, e -> new WrapperPlayServerSoundEffect((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_LIST_HEADER_AND_FOOTER, e -> new WrapperPlayServerPlayerListHeaderAndFooter((PacketSendEvent) e));
        map.put(PacketType.Play.Server.NBT_QUERY_RESPONSE, e -> new WrapperPlayServerNBTQueryResponse((PacketSendEvent) e));
        map.put(PacketType.Play.Server.COLLECT_ITEM, e -> new WrapperPlayServerCollectItem((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_TELEPORT, e -> new WrapperPlayServerEntityTeleport((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_ADVANCEMENTS, e -> new WrapperPlayServerUpdateAdvancements((PacketSendEvent) e));
        map.put(PacketType.Play.Server.UPDATE_ATTRIBUTES, e -> new WrapperPlayServerUpdateAttributes((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_EFFECT, e -> new WrapperPlayServerEntityEffect((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DECLARE_RECIPES, e -> new WrapperPlayServerDeclareRecipes((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TAGS, e -> new WrapperPlayServerTags((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CHAT_MESSAGE, e -> new WrapperPlayServerChatMessage((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ACKNOWLEDGE_BLOCK_CHANGES, e -> new WrapperPlayServerAcknowledgeBlockChanges((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SERVER_DATA, e -> new WrapperPlayServerServerData((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SYSTEM_CHAT_MESSAGE, e -> new WrapperPlayServerSystemChatMessage((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DELETE_CHAT, e -> new WrapperPlayServerDeleteChat((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CUSTOM_CHAT_COMPLETIONS, e -> new WrapperPlayServerCustomChatCompletions((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DISGUISED_CHAT, e -> new WrapperPlayServerDisguisedChat((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_INFO_REMOVE, e -> new WrapperPlayServerPlayerInfoRemove((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_INFO_UPDATE, e -> new WrapperPlayServerPlayerInfoUpdate((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DAMAGE_EVENT, e -> new WrapperPlayServerDamageEvent((PacketSendEvent) e));
        map.put(PacketType.Play.Server.HURT_ANIMATION, e -> new WrapperPlayServerHurtAnimation((PacketSendEvent) e));
        map.put(PacketType.Play.Server.BUNDLE, e -> new WrapperPlayServerBundle((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CHUNK_BATCH_END, e -> new WrapperPlayServerChunkBatchEnd((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CHUNK_BATCH_BEGIN, e -> new WrapperPlayServerChunkBatchBegin((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DEBUG_PONG, e -> new WrapperPlayServerDebugPong((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CONFIGURATION_START, e -> new WrapperPlayServerConfigurationStart((PacketSendEvent) e));
        map.put(PacketType.Play.Server.RESET_SCORE, e -> new WrapperPlayServerResetScore((PacketSendEvent) e));
        map.put(PacketType.Play.Server.RESOURCE_PACK_REMOVE, e -> new WrapperPlayServerResourcePackRemove((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TICKING_STATE, e -> new WrapperPlayServerTickingState((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TICKING_STEP, e -> new WrapperPlayServerTickingStep((PacketSendEvent) e));
        map.put(PacketType.Play.Server.COOKIE_REQUEST, e -> new WrapperPlayServerCookieRequest((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DEBUG_SAMPLE, e -> new WrapperPlayServerDebugSample((PacketSendEvent) e));
        map.put(PacketType.Play.Server.STORE_COOKIE, e -> new WrapperPlayServerStoreCookie((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TRANSFER, e -> new WrapperPlayServerTransfer((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PROJECTILE_POWER, e -> new WrapperPlayServerProjectilePower((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CUSTOM_REPORT_DETAILS, e -> new WrapperPlayServerCustomReportDetails((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SERVER_LINKS, e -> new WrapperPlayServerServerLinks((PacketSendEvent) e));
        map.put(PacketType.Play.Server.MOVE_MINECART, e -> new WrapperPlayServerMoveMinecart((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_CURSOR_ITEM, e -> new WrapperPlayServerSetCursorItem((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SET_PLAYER_INVENTORY, e -> new WrapperPlayServerSetPlayerInventory((PacketSendEvent) e));
        map.put(PacketType.Play.Server.ENTITY_POSITION_SYNC, e -> new WrapperPlayServerEntityPositionSync((PacketSendEvent) e));
        map.put(PacketType.Play.Server.PLAYER_ROTATION, e -> new WrapperPlayServerPlayerRotation((PacketSendEvent) e));
        map.put(PacketType.Play.Server.RECIPE_BOOK_ADD, e -> new WrapperPlayServerRecipeBookAdd((PacketSendEvent) e));
        map.put(PacketType.Play.Server.RECIPE_BOOK_REMOVE, e -> new WrapperPlayServerRecipeBookRemove((PacketSendEvent) e));
        map.put(PacketType.Play.Server.RECIPE_BOOK_SETTINGS, e -> new WrapperPlayServerRecipeBookSettings((PacketSendEvent) e));
        map.put(PacketType.Play.Server.TEST_INSTANCE_BLOCK_STATUS, e -> new WrapperPlayServerTestInstanceBlockStatus((PacketSendEvent) e));
        map.put(PacketType.Play.Server.WAYPOINT, e -> new WrapperPlayServerWaypoint((PacketSendEvent) e));
        map.put(PacketType.Play.Server.CLEAR_DIALOG, e -> new WrapperPlayServerClearDialog((PacketSendEvent) e));
        map.put(PacketType.Play.Server.SHOW_DIALOG, e -> new WrapperPlayServerShowDialog((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DEBUG_BLOCK_VALUE, e -> new WrapperPlayServerDebugBlockValue((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DEBUG_CHUNK_VALUE, e -> new WrapperPlayServerDebugChunkValue((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DEBUG_ENTITY_VALUE, e -> new WrapperPlayServerDebugEntityValue((PacketSendEvent) e));
        map.put(PacketType.Play.Server.DEBUG_EVENT, e -> new WrapperPlayServerDebugEvent((PacketSendEvent) e));
        map.put(PacketType.Play.Server.GAME_TEST_HIGHLIGHT_POS, e -> new WrapperPlayServerGameTestHighlightPos((PacketSendEvent) e));
        map.put(PacketType.Play.Client.CHAT_PREVIEW, e -> new WrapperPlayClientChatPreview((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.TELEPORT_CONFIRM, e -> new WrapperPlayClientTeleportConfirm((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.QUERY_BLOCK_NBT, e -> new WrapperPlayClientQueryBlockNBT((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SET_DIFFICULTY, e -> new WrapperPlayClientSetDifficulty((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CHAT_MESSAGE, e -> new WrapperPlayClientChatMessage((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CLIENT_STATUS, e -> new WrapperPlayClientClientStatus((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CLIENT_SETTINGS, e -> new WrapperPlayClientSettings((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.TAB_COMPLETE, e -> new WrapperPlayClientTabComplete((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.WINDOW_CONFIRMATION, e -> new WrapperPlayClientWindowConfirmation((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CLICK_WINDOW_BUTTON, e -> new WrapperPlayClientClickWindowButton((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CLICK_WINDOW, e -> new WrapperPlayClientClickWindow((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CLOSE_WINDOW, e -> new WrapperPlayClientCloseWindow((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLUGIN_MESSAGE, e -> new WrapperPlayClientPluginMessage((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.EDIT_BOOK, e -> new WrapperPlayClientEditBook((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.QUERY_ENTITY_NBT, e -> new WrapperPlayClientQueryEntityNBT((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.INTERACT_ENTITY, e -> new WrapperPlayClientInteractEntity((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.GENERATE_STRUCTURE, e -> new WrapperPlayClientGenerateStructure((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.KEEP_ALIVE, e -> new WrapperPlayClientKeepAlive((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.LOCK_DIFFICULTY, e -> new WrapperPlayClientLockDifficulty((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_POSITION, e -> new WrapperPlayClientPlayerPosition((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_POSITION_AND_ROTATION, e -> new WrapperPlayClientPlayerPositionAndRotation((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_ROTATION, e -> new WrapperPlayClientPlayerRotation((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_FLYING, e -> new WrapperPlayClientPlayerFlying((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.VEHICLE_MOVE, e -> new WrapperPlayClientVehicleMove((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.STEER_BOAT, e -> new WrapperPlayClientSteerBoat((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PICK_ITEM, e -> new WrapperPlayClientPickItem((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CRAFT_RECIPE_REQUEST, e -> new WrapperPlayClientCraftRecipeRequest((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_ABILITIES, e -> new WrapperPlayClientPlayerAbilities((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_DIGGING, e -> new WrapperPlayClientPlayerDigging((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.ENTITY_ACTION, e -> new WrapperPlayClientEntityAction((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.STEER_VEHICLE, e -> new WrapperPlayClientSteerVehicle((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PONG, e -> new WrapperPlayClientPong((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SET_DISPLAYED_RECIPE, e -> new WrapperPlayClientSetDisplayedRecipe((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SET_RECIPE_BOOK_STATE, e -> new WrapperPlayClientSetRecipeBookState((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.NAME_ITEM, e -> new WrapperPlayClientNameItem((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.RESOURCE_PACK_STATUS, e -> new WrapperPlayClientResourcePackStatus((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.ADVANCEMENT_TAB, e -> new WrapperPlayClientAdvancementTab((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SELECT_TRADE, e -> new WrapperPlayClientSelectTrade((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SET_BEACON_EFFECT, e -> new WrapperPlayClientSetBeaconEffect((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.HELD_ITEM_CHANGE, e -> new WrapperPlayClientHeldItemChange((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.UPDATE_COMMAND_BLOCK, e -> new WrapperPlayClientUpdateCommandBlock((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.UPDATE_COMMAND_BLOCK_MINECART, e -> new WrapperPlayClientUpdateCommandBlockMinecart((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CREATIVE_INVENTORY_ACTION, e -> new WrapperPlayClientCreativeInventoryAction((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.UPDATE_JIGSAW_BLOCK, e -> new WrapperPlayClientUpdateJigsawBlock((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.UPDATE_STRUCTURE_BLOCK, e -> new WrapperPlayClientSetStructureBlock((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.UPDATE_SIGN, e -> new WrapperPlayClientUpdateSign((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.ANIMATION, e -> new WrapperPlayClientAnimation((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SPECTATE, e -> new WrapperPlayClientSpectate((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT, e -> new WrapperPlayClientPlayerBlockPlacement((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.USE_ITEM, e -> new WrapperPlayClientUseItem((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CHAT_COMMAND, e -> new WrapperPlayClientChatCommand((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CHAT_ACK, e -> new WrapperPlayClientChatAck((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CHAT_SESSION_UPDATE, e -> new WrapperPlayClientChatSessionUpdate((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CHUNK_BATCH_ACK, e -> new WrapperPlayClientChunkBatchAck((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CONFIGURATION_ACK, e -> new WrapperPlayClientConfigurationAck((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.DEBUG_PING, e -> new WrapperPlayClientDebugPing((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SLOT_STATE_CHANGE, e -> new WrapperPlayClientSlotStateChange((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CHAT_COMMAND_UNSIGNED, e -> new WrapperPlayClientChatCommandUnsigned((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.COOKIE_RESPONSE, e -> new WrapperPlayClientCookieResponse((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.DEBUG_SAMPLE_SUBSCRIPTION, e -> new WrapperPlayClientDebugSampleSubscription((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CLIENT_TICK_END, e -> new WrapperPlayClientClientTickEnd((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SELECT_BUNDLE_ITEM, e -> new WrapperPlayClientSelectBundleItem((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_INPUT, e -> new WrapperPlayClientPlayerInput((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PICK_ITEM_FROM_BLOCK, e -> new WrapperPlayClientPickItemFromBlock((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PICK_ITEM_FROM_ENTITY, e -> new WrapperPlayClientPickItemFromEntity((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.PLAYER_LOADED, e -> new WrapperPlayClientPlayerLoaded((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.SET_TEST_BLOCK, e -> new WrapperPlayClientSetTestBlock((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.TEST_INSTANCE_BLOCK_ACTION, e -> new WrapperPlayClientTestInstanceBlockAction((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CHANGE_GAME_MODE, e -> new WrapperPlayClientChangeGameMode((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.CUSTOM_CLICK_ACTION, e -> new WrapperPlayClientCustomClickAction((PacketReceiveEvent) e));
        map.put(PacketType.Play.Client.DEBUG_SUBSCRIPTION_REQUEST, e -> new WrapperPlayClientDebugSubscriptionRequest((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Server.PLUGIN_MESSAGE, e -> new WrapperConfigServerPluginMessage((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.DISCONNECT, e -> new WrapperConfigServerDisconnect((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.CONFIGURATION_END, e -> new WrapperConfigServerConfigurationEnd((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.KEEP_ALIVE, e -> new WrapperConfigServerKeepAlive((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.PING, e -> new WrapperConfigServerPing((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.REGISTRY_DATA, e -> new WrapperConfigServerRegistryData((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.RESOURCE_PACK_SEND, e -> new WrapperConfigServerResourcePackSend((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.UPDATE_ENABLED_FEATURES, e -> new WrapperConfigServerUpdateEnabledFeatures((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.RESOURCE_PACK_REMOVE, e -> new WrapperConfigServerResourcePackRemove((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.COOKIE_REQUEST, e -> new WrapperConfigServerCookieRequest((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.RESET_CHAT, e -> new WrapperConfigServerResetChat((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.STORE_COOKIE, e -> new WrapperConfigServerStoreCookie((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.TRANSFER, e -> new WrapperConfigServerTransfer((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.SELECT_KNOWN_PACKS, e -> new WrapperConfigServerSelectKnownPacks((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.CUSTOM_REPORT_DETAILS, e -> new WrapperConfigServerCustomReportDetails((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.SERVER_LINKS, e -> new WrapperConfigServerServerLinks((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.CLEAR_DIALOG, e -> new WrapperConfigServerClearDialog((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.SHOW_DIALOG, e -> new WrapperConfigServerShowDialog((PacketSendEvent) e));
        map.put(PacketType.Configuration.Server.CODE_OF_CONDUCT, e -> new WrapperConfigServerCodeOfConduct((PacketSendEvent) e));
        map.put(PacketType.Configuration.Client.CLIENT_SETTINGS, e -> new WrapperConfigClientSettings((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.PLUGIN_MESSAGE, e -> new WrapperConfigClientPluginMessage((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.CONFIGURATION_END_ACK, e -> new WrapperConfigClientConfigurationEndAck((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.KEEP_ALIVE, e -> new WrapperConfigClientKeepAlive((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.PONG, e -> new WrapperConfigClientPong((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.RESOURCE_PACK_STATUS, e -> new WrapperConfigClientResourcePackStatus((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.COOKIE_RESPONSE, e -> new WrapperConfigClientCookieResponse((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.SELECT_KNOWN_PACKS, e -> new WrapperConfigClientSelectKnownPacks((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.CUSTOM_CLICK_ACTION, e -> new WrapperConfigClientCustomClickAction((PacketReceiveEvent) e));
        map.put(PacketType.Configuration.Client.ACCEPT_CODE_OF_CONDUCT, e -> new WrapperConfigClientAcceptCodeOfConduct((PacketReceiveEvent) e));
        map.put(PacketType.Login.Server.DISCONNECT, e -> new WrapperLoginServerDisconnect((PacketSendEvent) e));
        map.put(PacketType.Login.Server.ENCRYPTION_REQUEST, e -> new WrapperLoginServerEncryptionRequest((PacketSendEvent) e));
        map.put(PacketType.Login.Server.LOGIN_SUCCESS, e -> new WrapperLoginServerLoginSuccess((PacketSendEvent) e));
        map.put(PacketType.Login.Server.SET_COMPRESSION, e -> new WrapperLoginServerSetCompression((PacketSendEvent) e));
        map.put(PacketType.Login.Server.LOGIN_PLUGIN_REQUEST, e -> new WrapperLoginServerPluginRequest((PacketSendEvent) e));
        map.put(PacketType.Login.Server.COOKIE_REQUEST, e -> new WrapperLoginServerCookieRequest((PacketSendEvent) e));
        map.put(PacketType.Login.Client.LOGIN_START, e -> new WrapperLoginClientLoginStart((PacketReceiveEvent) e));
        map.put(PacketType.Login.Client.ENCRYPTION_RESPONSE, e -> new WrapperLoginClientEncryptionResponse((PacketReceiveEvent) e));
        map.put(PacketType.Login.Client.LOGIN_PLUGIN_RESPONSE, e -> new WrapperLoginClientPluginResponse((PacketReceiveEvent) e));
        map.put(PacketType.Login.Client.LOGIN_SUCCESS_ACK, e -> new WrapperLoginClientLoginSuccessAck((PacketReceiveEvent) e));
        map.put(PacketType.Login.Client.COOKIE_RESPONSE, e -> new WrapperLoginClientCookieResponse((PacketReceiveEvent) e));
        map.put(PacketType.Status.Server.RESPONSE, e -> new WrapperStatusServerResponse((PacketSendEvent) e));
        map.put(PacketType.Status.Server.PONG, e -> new WrapperStatusServerPong((PacketSendEvent) e));
        map.put(PacketType.Status.Client.REQUEST, e -> new WrapperStatusClientRequest((PacketReceiveEvent) e));
        map.put(PacketType.Status.Client.PING, e -> new WrapperStatusClientPing((PacketReceiveEvent) e));
        map.put(PacketType.Handshaking.Client.HANDSHAKE, e -> new WrapperHandshakingClientHandshake((PacketReceiveEvent) e));
    }

    public static Function<ProtocolPacketEvent, PacketWrapper<?>> getWrapper(PacketTypeCommon packetType) {
        Function<ProtocolPacketEvent, PacketWrapper<?>> constructor = map.get(packetType);
        if (constructor == null)
            throw new IllegalArgumentException("No Constructor found for " + packetType);

        return constructor;
    }
}
